 You can dowload dataset from here:
 
## Dataset:
https://github.com/campusx-official/100-days-of-machine-learning/blob/main/day28-column-transformer/covid_toy.csv

### Column Transformer in Machine Learning | How to use ColumnTransformer in Sklearn

ColumnTransformer is a Scikit-Learn utility that applies different transformations to different columns of a dataset and combines the transformed features into a single output for machine learning models.

### Benefits

Different columns par different preprocessing.

Clean and organized pipeline.

Train aur test data par same transformations apply karna easy.

Machine Learning workflows me widely used.

In [1]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [6]:
df = pd.read_csv('covid_toy (1).csv')

In [7]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [10]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [8]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [13]:
X_train

    age  gender  fever   cough       city
61   81  Female   98.0  Strong     Mumbai
58   23    Male   98.0  Strong     Mumbai
52   47  Female  100.0  Strong  Bangalore
55   81  Female  101.0    Mild     Mumbai
75    5    Male  102.0    Mild    Kolkata
..  ...     ...    ...     ...        ...
87   47    Male  101.0  Strong  Bangalore
18   64  Female   98.0    Mild  Bangalore
77    8  Female  101.0    Mild    Kolkata
35   82  Female  102.0  Strong  Bangalore
78   11    Male  100.0    Mild  Bangalore

[80 rows x 5 columns]

## 1. Normal

In [15]:
## adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [16]:
# OrdinalEncoding -> cough
oe = OrdinalEncoder(categories= [['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [19]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first', sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [20]:
# Extracting Age
X_train_age = X_train.drop(columns= ['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age

array([[81],
       [23],
       [47],
       [81],
       [ 5],
       [73],
       [82],
       [27],
       [ 5],
       [42],
       [84],
       [49],
       [34],
       [46],
       [69],
       [69],
       [68],
       [75],
       [42],
       [10],
       [ 5],
       [80],
       [83],
       [74],
       [18],
       [14],
       [42],
       [12],
       [80],
       [13],
       [82],
       [64],
       [27],
       [51],
       [12],
       [15],
       [49],
       [38],
       [40],
       [65],
       [49],
       [79],
       [73],
       [19],
       [55],
       [26],
       [33],
       [38],
       [19],
       [11],
       [20],
       [71],
       [59],
       [69],
       [60],
       [44],
       [22],
       [65],
       [60],
       [16],
       [24],
       [54],
       [65],
       [70],
       [51],
       [66],
       [51],
       [19],
       [65],
       [25],
       [16],
       [71],
       [10],
       [27],
       [34],
       [47],
       [64],
       [ 8],
       [82],
       [11]])

In [21]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)

# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

## By using Column Transformer

In [22]:
from sklearn.compose import ColumnTransformer

In [31]:
transformer = ColumnTransformer(transformers =[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder = 'passthrough')

In [33]:
transformer.fit_transform(X_train).shape

(80, 7)

In [34]:
transformer.transform(X_test).shape

(20, 7)